export const HomeObjOne = {
    lightBg: false,
    primary: true,
    imgStart: '', 
    lightTopLine: true,
    topLine: 'Marketing Agency',
    lightText: true,
    headLine: 'Lead Generation Specialist for Online Businesses.',
    lightTextDesc: true,
    description: 'We help business owners increase their revenue. Our team of unique specialist can help you achieve your goals',
    buttonLabel: 'Get Started',
    start: true,
    img: require('../../images/CodeReview.svg').default,
    alt: 'Image Test',
}

export const HomeObjTwo = {
    lightBg: true,
    primary: false,
    imgStart: 'start', 
    lightTopLine: false,
    topLine: 'Marketing Agency',
    lightText: false,
    headLine: 'Lead Generation Specialist for Online Businesses.',
    lightTextDesc: false,
    description: 'We help business owners increase their revenue. Our team of unique specialist can help you achieve your goals',
    buttonLabel: 'Get Started',
    start: true,
    img: require('../../images/Marketing.svg').default,
    alt: 'Image Test',
}

export const HomeObjThree = {
    lightBg: false,
    primary: true,
    imgStart: '', 
    lightTopLine: true,
    topLine: 'Marketing Agency',
    lightText: true,
    headLine: 'Lead Generation Specialist for Online Businesses.',
    lightTextDesc: true,
    description: 'We help business owners increase their revenue. Our team of unique specialist can help you achieve your goals',
    buttonLabel: 'Get Started',
    start: true,
    img: require('../../images/Visionary.svg').default,
    alt: 'Image Test',
}

export const HomeObjFour = {
    lightBg: false,
    primary: true,
    imgStart: 'start', 
    lightTopLine: true,
    topLine: 'Marketing Agency',
    lightText: true,
    headLine: 'Lead Generation Specialist for Online Businesses.',
    lightTextDesc: true,
    description: 'We help business owners increase their revenue. Our team of unique specialist can help you achieve your goals',
    buttonLabel: 'Get Started',
    start: true,
    img: require('../../images/Analisys.svg').default,
    alt: 'Image Test',
}